In [1]:
import numpy as np
# untuk menggunakan numpy harus mengetik np

In [2]:
angka = [1,2,3]

In [3]:
angkanp = np.array(angka)

In [4]:
angkanp

array([1, 2, 3])

In [6]:
angka*3 # ini hanya list biasa tidak pakai numpy

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [8]:
angkanp*3 #ini list memakai numpy

array([3, 6, 9])

In [13]:
versilist = [[1,2,3],[4,5,6],[7,8,9]]
versilist #ini list di dalam list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
versinumpy = np.array(versilist)
versinumpy #menghasilkan matriks 2 dimensi. ini matrik 3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# disini pun ada fungsi dan range

In [17]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
np.arange(0,30,5) #jadi ini 0 -30 dan 5 ini adalah jaraknya. dan angka 30 tidak dimasukan

array([ 0,  5, 10, 15, 20, 25])

In [24]:
# di numpy ada bisa membangkitkan angka 0
np.zeros(5) #angka sebenazrnya adalah 0

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros((2,4)) #ini matrik 2 dimensi. semua berisi 0. dimana baris x kolom

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
#kita pun bisa membangkitkan angka 1
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
#kita pun bisa membangkitkan range 11 dimensi dan jaraknya sama besar dengan angka yang di tentukan juga
np.linspace(0,10,8) #jadi disini akan membuat array 0-10 akan di pecah jadi 8 dan jarak pecahannya pun sama besar

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

#### Ini range 1 demnsi karna 2 kurung tutup. kalo ada 2 dimensi maka ada 2 kurung tutup
#### Kapan ini ones,linspace,arange,zeros tergantung di butuhkan
#### IDENTITY MATRIKS
#### Di numpy ada suatu fungsi dalam membangkitkan identity matriks
#### Ada maktrik segita, dan persegi

In [42]:
np.eye(6) #jadi ada 6x6 dan ada 1 diagonal

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])