In [1]:
import numpy as np

In [2]:
# bilangan distribusi uniform (0-1)
np.random.rand(8) # 8 ini merupakan bilangan berjumlah 8

array([0.86672483, 0.22950419, 0.37244556, 0.47440924, 0.0883052 ,
       0.91308021, 0.01944595, 0.24616636])

In [3]:
# bilangan distribusi uniform (0-1) jadi 2 dimensi
np.random.rand(6,4) #jadi ada 4 kolom dan 6 baris

array([[0.74459298, 0.45141538, 0.20433962, 0.9268278 ],
       [0.51553449, 0.63400766, 0.46813029, 0.82087406],
       [0.76224803, 0.57616451, 0.50818392, 0.58211568],
       [0.05171314, 0.11208741, 0.73005181, 0.4256437 ],
       [0.13364313, 0.79499902, 0.45435414, 0.71184078],
       [0.08401688, 0.00675672, 0.70017051, 0.64914394]])

In [4]:
# Bilangan distribusi normal (gaussion)
np.random.rand(12) # ini 1 dimensi

array([0.19292737, 0.36832337, 0.87735223, 0.16709385, 0.84131636,
       0.29879768, 0.5560311 , 0.20978735, 0.55777154, 0.34113664,
       0.88906529, 0.4829359 ])

In [5]:
# Bilangan distribusi normal (gaussion)
np.random.rand(12,4) # ini matriks 2 dimensi

array([[0.45187797, 0.50160864, 0.82744999, 0.10638754],
       [0.83820223, 0.02737223, 0.46637467, 0.94429218],
       [0.80520708, 0.83561884, 0.26517101, 0.86019807],
       [0.36534321, 0.88355343, 0.63289869, 0.07935982],
       [0.60245465, 0.35518938, 0.6211408 , 0.41175986],
       [0.54417523, 0.77450078, 0.06237121, 0.03678969],
       [0.64675391, 0.41629557, 0.96461509, 0.55757693],
       [0.28817545, 0.69357823, 0.34918213, 0.26468422],
       [0.72401994, 0.82664235, 0.08554811, 0.1313336 ],
       [0.90935132, 0.78034079, 0.21961908, 0.98110603],
       [0.45798985, 0.92064262, 0.42170751, 0.29010701],
       [0.48026306, 0.36108325, 0.30836311, 0.26468789]])

In [6]:
# Kita bisa mempersingkat penulisan di atas dengan
from numpy.random import rand, randint

In [7]:
rand(6,4)

array([[0.09749887, 0.36559928, 0.31963945, 0.23065938],
       [0.7401585 , 0.48161447, 0.66038325, 0.72039411],
       [0.82023885, 0.4457216 , 0.07772773, 0.89496619],
       [0.93018556, 0.31992252, 0.11636251, 0.57391678],
       [0.43879282, 0.42185653, 0.3113307 , 0.74313651],
       [0.85969907, 0.85508711, 0.42906522, 0.71888126]])

In [8]:
randint(0,8)

3

In [9]:
randint(0,10,2)

array([5, 1])

##### Hasil semua operasi ini bisa kita masukan ke sebuah variabel

In [10]:
bilangan = randint(0,140,20)

In [11]:
bilangan

array([  1, 115,  87, 123,  19,  31, 105,  18,  21,   8, 135,  85,  75,
        85, 120, 100,  53, 113,  90,  39])

#### Kita bisa merubah dengan sebuah matriks
#### Bilangan nya ini tidak lebih dari 20. bilangan yang diatas

In [12]:
bilangan.reshape(4,5)

array([[  1, 115,  87, 123,  19],
       [ 31, 105,  18,  21,   8],
       [135,  85,  75,  85, 120],
       [100,  53, 113,  90,  39]])

In [13]:
from numpy.random import rand, randn, randint

In [14]:
randint(0,3,5) # bialngan ini kan 0-3 tapi, 3 nya tidak di hitung karna ada slicing

array([1, 0, 1, 1, 1])

In [15]:
item = randint(0,10,20).reshape(5,4)

In [16]:
item

array([[3, 0, 4, 5],
       [0, 8, 3, 3],
       [8, 7, 1, 3],
       [6, 6, 0, 0],
       [0, 0, 5, 2]])

In [17]:
item.reshape(2,10)

array([[3, 0, 4, 5, 0, 8, 3, 3, 8, 7],
       [1, 3, 6, 6, 0, 0, 0, 0, 5, 2]])

In [18]:
item 

array([[3, 0, 4, 5],
       [0, 8, 3, 3],
       [8, 7, 1, 3],
       [6, 6, 0, 0],
       [0, 0, 5, 2]])

In [19]:
#kita pun bisa menugaskan ulang
item = item.reshape(2,10)

In [20]:
item

array([[3, 0, 4, 5, 0, 8, 3, 3, 8, 7],
       [1, 3, 6, 6, 0, 0, 0, 0, 5, 2]])

##### Buat matrik 1 demensi dan 2 dimensi

In [21]:
item2 = randint(0,120,20)

In [22]:
item3 = randint(0,120,20).reshape(4,5)

In [23]:
item2

array([ 27,  27,  90,  44,  82, 103,  21,  11, 101, 104,  35,  41,  79,
        70,  43,  93,  52, 102,  48,  41])

In [24]:
item3

array([[115,   5,  18,  85,  62],
       [ 57, 103,  34,  64, 101],
       [ 29, 108,  92,  89,  15],
       [ 35,   9,  68,  23, 103]])

#### Fungsi agar tau angka maksimalnya dimana

In [25]:
item3.max()

115

In [26]:
item2.max()

104

In [27]:
item2.min()

11

In [28]:
item3.min()

5

In [29]:
# agar kita tau indkesnya 
item2.argmax()

9

In [30]:
item3.argmax()

0

In [31]:
item2.argmin()

7

In [32]:
item3.argmin()

1

In [33]:
item2.shape #agar tau dimaensi area dimana

(20,)

In [34]:
item3.shape

(4, 5)

In [35]:
item2.dtype #kita pun bisa tau datanya

dtype('int32')

In [36]:
item3.dtype

dtype('int32')

#### Cara membuat indexing di numpy sama dengan hal nya di python

In [37]:
box = np.arange(0,12)

In [38]:
box

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
box[6] # kita bisa mengambil index

6

In [40]:
box[4:] #kita pun bisa memakai slicing

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
box[4:8]

array([4, 5, 6, 7])

In [42]:
box[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [43]:
box1 = box[:7]

In [44]:
box1

array([0, 1, 2, 3, 4, 5, 6])

In [45]:
box1[:] = 20

In [46]:
box1 #kita bisa mengganti variebel pada box1. tapi kita kita memakai python tidak lah berpengaruh

array([20, 20, 20, 20, 20, 20, 20])

In [47]:
box

array([20, 20, 20, 20, 20, 20, 20,  7,  8,  9, 10, 11])

#### Kita bisa memakai copy jika memakai data dari variabel lain

In [48]:
boxi = np.arange(0,13)

In [49]:
boxi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [50]:
boxi[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
box1 = boxi[:6]

In [52]:
box1

array([0, 1, 2, 3, 4, 5])

In [53]:
box1[:] = 220

In [54]:
box1

array([220, 220, 220, 220, 220, 220])

In [55]:
boxi

array([220, 220, 220, 220, 220, 220,   6,   7,   8,   9,  10,  11,  12])

In [56]:
boxi = box1.copy()

In [57]:
boxi

array([220, 220, 220, 220, 220, 220])

In [58]:
boxi[:] = 100

In [59]:
boxi

array([100, 100, 100, 100, 100, 100])

In [60]:
box1 #seharusnya ada angka yang berbeda

array([220, 220, 220, 220, 220, 220])

##### Cara mendefinisikan sebuah variabel menjadi matrik 2 dimensi

In [61]:
error = np.array([[2,3,4],[5,6,7],[8,9,10]])

In [62]:
error

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

##### Kita bisa men indeksikan mirip dengan python

In [63]:
error[0][0]

2

In [64]:
error[1]

array([5, 6, 7])

In [65]:
error[2][2]

10

In [66]:
error[2,2] #ini cara yang lebih mudah untuk mengambil angka 10

10

##### Disini pun jika ingin menggunakan slicing sama seperti di python

In [67]:
error

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [68]:
error[1:2,1:2]

array([[6]])

##### Kita bisa menggunakan slicing dengan boolean

In [69]:
code = np.arange(1,13)

In [70]:
code

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [71]:
none = code>6

In [72]:
none # yang true dari 7-11

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

In [73]:
code = code[none]

In [74]:
none #seharunya muncul angka 7,8,9,10,11,12

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

#### Kita bisa mempercepat caraya

In [75]:
code[code>5]

array([ 7,  8,  9, 10, 11, 12])

In [76]:
code = code[code>5] #ini dengan cara mendeinisikan

In [77]:
code

array([ 7,  8,  9, 10, 11, 12])